language: node_js
script: npm run bootstrap && npm run build && npm run test && npm run coverage
after_success:
  - cat ./packages/mobx-state-tree/coverage/lcov.info|./packages/mobx-state-tree/node_modules/coveralls/bin/coveralls.js
node_js:
  - "6.10.1"